___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

the #arange works exactly like #range function used with loops

In [39]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return 1-D Array evenly spaced numbers over a specified interval.



linspace is a NumPy function used to generate evenly spaced numbers over a specified interval.

numpy.linspace(start, stop, num=50, endpoint=True)

Parameters Explained
1. start

The starting value of the sequence

2. stop

The ending value of the sequence

3. num (optional)

Number of values to generate

Default is 50

4. endpoint (optional)

If True → includes the stop value

If False → excludes the stop value

In [43]:
np.linspace(0,5,50,endpoint=True)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [47]:
np.linspace(10,20,20,endpoint=False)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

## eye

Creates an identity matrix

## What does the eye() function do in NumPy?

The eye() function in NumPy is used to create an identity matrix .

np.eye(N, M=None, k=0)

### Parameters Explained
1. N

Number of rows

2. M (optional)

Number of columns

If not given → matrix will be square (N × N)

3. k (optional)

Position of the diagonal

k = 0 → main diagonal (default)

k > 0 → above main diagonal

k < 0 → below main diagonal

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.eye(3,4) # an square Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [52]:
np.eye(6,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
# k = 0 → main diagonal (default)
np.eye(4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# k > 0 → above main diagonal
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [60]:
# k < 0 → below main diagonal
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## Random 

Numpy also has lots of ways to create random number arrays:

## rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

### 0 ≤ random number < 1

In [63]:
np.random.rand(2)

array([0.09622776, 0.95370571])

In [78]:
arr = np.random.rand(5,5)
arr

array([[0.53789244, 0.22167347, 0.57800148, 0.53626789, 0.29865222],
       [0.1584797 , 0.30829882, 0.55975472, 0.09136858, 0.53956987],
       [0.80040255, 0.48559111, 0.42687465, 0.18180684, 0.61954779],
       [0.75569214, 0.74730658, 0.74828168, 0.50982422, 0.5788803 ],
       [0.36230058, 0.72961008, 0.53821848, 0.22922971, 0.80455728]])

## randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

### What does randn() do in NumPy?

np.random.randn() generates random numbers from a normal (Gaussian) distribution.

📌 This distribution has:

### Mean (μ) = 0

### Standard deviation (σ) = 1

So values can be:

Positive or negative

Small or large (but most are near 0)

In [81]:
np.random.randn(5)

array([-0.36212197,  0.05303375,  0.63656934, -1.15607185, -2.24209733])

In [18]:
np.random.randn(5,5)

array([[ 0.49863858, -0.72639639, -1.53186128, -1.41577648,  0.35162426],
       [-0.28961919,  1.29803131, -2.22212046, -0.19917819,  0.79000371],
       [-2.58946808, -2.13186365, -1.25656999, -1.05307592, -0.40118668],
       [ 1.29964558, -1.02195763, -0.92544605,  0.32747456, -0.39361934],
       [ 0.3126958 ,  0.67574321,  0.36450613, -0.32551303,  0.77171884]])

## randint
Return random integers from `low` (inclusive) to `high` (exclusive).

### What does randint() do in NumPy?

np.random.randint() generates random integers between a given range.

Values are whole numbers

Lower bound is inclusive

Upper bound is exclusive

``np.random.randint(low, high=None, size=None)``

### Parameters Explained
1️⃣ low

Minimum value (included)

2️⃣ high (optional)

Maximum value (excluded)

If not given → range is 0 to low

3️⃣ size (optional)

Shape of the output (single value, 1D, 2D, etc.)

## 2️⃣ 1D Array

In [138]:
np.random.randint(1,100)

59

In [149]:
np.random.randint(1,100,10)

array([62,  9, 74, 67,  3, 27, 63, 21, 91, 20], dtype=int32)

## 2️⃣ 2D Array

In [154]:
np.random.randint(1,100,size=(3,3))

array([[49, 48, 52],
       [ 5, 48, 59],
       [65, 72, 78]], dtype=int32)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([31, 24,  0, 47, 17,  6, 41, 38,  1,  6], dtype=int32)

## Reshape
Returns an array containing the same data with a new shape.

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [25]:
ranarr

array([31, 24,  0, 47, 17,  6, 41, 38,  1,  6], dtype=int32)

In [26]:
ranarr.max()

np.int32(47)

In [27]:
ranarr.argmax()

np.int64(3)

In [28]:
ranarr.min()

np.int32(0)

In [29]:
ranarr.argmin()

np.int64(2)

## Shape

Shape is an attribute that arrays have (not a method):

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [35]:
arr.dtype

dtype('int64')

# Great Job!